server {
  listen 80;
  server_name _;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Request-Id $request_id;
  proxy_set_header X-Correlation-Id $request_id;

  location /api/v1/ {
    proxy_pass http://backend-spring:8080;
  }

  location /actuator/ {
    proxy_pass http://backend-spring:8080;
  }

  location /swagger-ui/ {
    proxy_pass http://backend-spring:8080;
  }

  location /v3/api-docs/ {
    proxy_pass http://backend-spring:8080;
  }

  location /external/ {
    proxy_pass http://middleware-nest:3000;
  }

  location /health {
    proxy_pass http://middleware-nest:3000;
  }
}

